// mobile/lib/petTwin.ts
// Mobile client for Pet Twin — mirrors web/lib/petTwin.ts. The daily card is
// generated by the already-deployed web route (/api/ai/pet-twin), which owns
// the cadence gate (free weekly / Pro daily), the honesty-grounding, and the
// server-only write to dogs/{uid}/moments. The app never writes moments; it
// reads the realtime stream and POSTs (with a Firebase ID token) to ask for a
// new card.

import { collection, limit, onSnapshot, orderBy, query } from 'firebase/firestore';
import { getFirebase } from './firebase';

export interface PetTwinMoment {
  id: string;
  thought: string;
  mood: string;
  moodEmoji: string;
  sourceKind: string;
  /** The literally-true thing this card reacted to — shown as the source chip. */
  sourceLabel: string;
  createdAt: number;
  model?: string;
  promptVersion?: string;
}

export interface GenerateResult {
  /** null only in the rare "another request is generating right now" case —
   *  the realtime listener resolves the card the moment it lands. */
  moment: PetTwinMoment | null;
  throttled: boolean;
  isPro: boolean;
  nextAllowedMs?: number;
}

function webBase(): string | null {
  return (
    process.env.EXPO_PUBLIC_WEB_URL?.trim().replace(/\/$/, '') ||
    process.env.EXPO_PUBLIC_PAYMENTS_API_URL?.trim().replace(/\/$/, '') ||
    null
  );
}

export function isPetTwinConfigured(): boolean {
  return Boolean(webBase());
}

async function currentIdToken(): Promise<string> {
  const user = getFirebase().auth.currentUser;
  if (!user) throw new Error('You need to be signed in.');
  return user.getIdToken();
}

/** Ask for a new card. The server returns the existing one (throttled) if it's
 *  too soon for this tier, so callers can treat both the same way. */
export async function generatePetTwin(): Promise<GenerateResult> {
  const base = webBase();
  if (!base) throw new Error('Pet Twin is not configured for this build.');
  const idToken = await currentIdToken();
  const res = await fetch(`${base}/api/ai/pet-twin`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${idToken}` },
  });
  const data = await res.json().catch(() => ({} as { error?: string }));
  if (!res.ok) {
    throw new Error((data as { error?: string })?.error || 'Could not get today\'s card. Try again.');
  }
  // A 200 with moment:null means another request is mid-generation — not an
  // error; the caller keeps whatever the listener shows and it self-heals.
  return data as GenerateResult;
}

/** Realtime listener for the most recent moment (today's card). */
export function onLatestMoment(
  dogId: string,
  callback: (moment: PetTwinMoment | null) => void,
): () => void {
  const { db } = getFirebase();
  const q = query(
    collection(db, 'dogs', dogId, 'moments'),
    orderBy('createdAt', 'desc'),
    limit(1),
  );
  return onSnapshot(
    q,
    (snap) => {
      const docSnap = snap.docs[0];
      callback(docSnap ? ({ id: docSnap.id, ...docSnap.data() } as PetTwinMoment) : null);
    },
    () => callback(null),
  );
}
